url: 'https://finessi.de'
baseurl: ''
title: 'Finessi_'

plugins:
  - jekyll-postcss-v2
  - jekyll-seo-tag

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock

collections:
  about:
    sort_by: order
  socials:
    sort_by: order
  projects:
    sort_by: order
  references:
    sort_by: order

tagline: "Aufklärung zu LGBTQIA+ Themen"
description: "FiNessi ist on- und offline in Öffentlichkeitsarbeit aktiv. Viel Aufklärungsarbeit zu Geschlecht und Transsein, zu Umwelt- und Klimaschutz. Live auf Twitch, vorproduziert auf YouTube, in Interviews und Dokumentation bei Print und Video."
locale: de_DE

twitter:
  username: finessi_
  card: summary
  
author:
  twitter: finessi_
  name: Finessi_
  url: https://twitter.com/finessi_
  picture: jekyll-nessi/assets/images/nessi.webp
