url: ''
baseurl: ''
title: 'Finessi_'

plugins:
  - jekyll-postcss-v2

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock

collections:
  about:
    sort_by: order
  socials:
    sort_by: order
  projects:
    sort_by: order
  references:
    sort_by: order
