name: Build page

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock

    steps:
      - uses: actions/checkout@v2
      
      - name: Jekyll Picture Tag dependencies install
        run: sudo apt install libvips-tools libvips42 libvips-dev
        
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
     
      - name: Build page
        run: | 
          bundle install
          bundle exec jekyll build

      - name: Setup SSH Key
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.PRIVATE_KEY }}"
      - name: rsync to target
        run: rsync -Pr -e "ssh -o StrictHostKeyChecking=accept-new" _site/ refuge@refuge.uber.space:/var/www/virtual/refuge/nessi-beta.refuge.uber.space
